### ISSUE TITLE
Link to sample in README is 404ing.

### ISSUE THREAD

**Issue by jezmck** [PiSupply/rak811-python#11]

**Comment by ryanteck** [comment]
Hi,

We are in the progress of changing the documentation to use a better library written by one of our beta testers located at https://github.com/AmedeeBulle/pyrak811

We'll be updating these shortly at https://github.com/PiSupply/IoTLoRaRange/tree/master/IoT%20LoRa%20Raspberry%20Pi%20Node%20pHAT and https://pypi.org/project/rak811/
